POST {{ api }}/api/v1/auth/login
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{}

> {%
 client.test("capture access token and set to header", function () {
     var access_token = response.body["accessToken"]
     client.global.set("access_token", access_token)
 })
%}
###

GET {{ api }}/api/v1/meta/folders
Authorization: Bearer {{ access_token }}
Accept: application/json

###

