steps = [
    {
        'name': 'Step Course Creation Request',
        'included': False,
        'start': ['Course submit request is received', ],
        'end': ['Finish course submit request', ],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step User Preparation',
        'included': False,
        'start': ['Prepare user: ', ],
        'end': ['User: ', 'was prepared', ],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step License Preparation',
        'included': False,
        'start': ['Prepare license: '],
        'end': ['License was prepared: ', ],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Sub-account Preparation',
        'included': False,
        'start': ['Prepare sub-account: ', ],
        'end': ['Sub-account: ', 'was prepared.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Course Preparation',
        'included': False,
        'start': ['Prepare course: ', ],
        'end': ['Course: ', ' was prepared.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Course Sections Preparation',
        'included': False,
        'start': ['Prepare sections for course: ', ],
        'end': ['Sections for course: ', ' were prepared.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Association Preparation',
        'included': False,
        'start': ['Prepare association with blueprint: ', ],
        'end': ['Association with blueprint: ', ' was prepared.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Queue Preparation',
        'included': False,
        'start': ['Send a message to SQS queue', ],
        'end': ['Message was sent  to SQS queue', ],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Steps Before Blueprint Migration',
        'included': True,
        'start': ['Course submit request is received', ],
        'end': ['Message was sent  to SQS queue ', ],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Blueprint Migration',
        'included': True,
        'start': ['migration_queued', ],
        'end': ['migration_done', ],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Steps After Blueprint Migration',
        'included': True,
        'start': ['Prepare LTI consumer for institution:', ],
        'end': ['Course setup job: ', 'was finished successfully.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step LTI Consumer Preparation',
        'included': False,
        'start': ['Prepare LTI consumer for institution: ', ],
        'end': ['LTI consumer for institution: ', 'was prepared.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Enrollment Preparation',
        'included': False,
        'start': ['Prepare enrollment of teacher: ', ],
        'end': ['Enrollment of teacher: ', 'was prepared.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Success Course Setup Notification',
        'included': False,
        'start': ['Preparing notification about successfully setting up the course', ],
        'end': ['Notification about successfully setting up the course', 'was sent successfully.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Step Success Course Readiness Notification',
        'included': False,
        'start': ['Preparing notification about course readiness', ],
        'end': ['Notification about course readiness', 'was sent successfully.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
    {
        'name': 'Total Time Course Creation',
        'included': True,
        'start': ['Start processing course setup job', ],
        'end': ['Course setup job: ', 'was finished successfully.'],
        'start_ts': '',
        'end_ts': '',
        'time': '',
        'stat': [],
    },
]
